version: '3.8'

services:
  db:
    image: postgres:15
    container_name: booker_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env_docker
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booker_redis

  booker:
    build: 
      context: .
    container_name: booker_app
    env_file:
      - .env_docker
    depends_on:
      - db
      - redis
    command: ["/booker/docker/app.sh"]
    ports:
      - 9000:8000

  celery:
    build: 
      context: .
    container_name: booker_celery
    depends_on:
      - redis
    command: ["/booker/docker/celery.sh", "celery"]
    env_file:
      - .env_docker

  flower:
    build: 
      context: .
    container_name: booker_flower
    depends_on:
      - redis
    command: ["/booker/docker/celery.sh", "flower"]
    env_file:
      - .env_docker

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
      
volumes:
  postgresdata:
  grafanadata:
  prometheusdata:
